# Generated by Django 5.2.7 on 2025-10-27 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Assistant SmartCity', max_length=100, verbose_name="Nom de l'assistant")),
                ('system_prompt', models.TextField(default='Tu es un assistant intelligent spécialisé dans la gestion de ville intelligente (SmartCity). Tu peux aider avec la gestion de véhicules, la mobilité urbaine, les transports, et toutes questions liées à la ville intelligente. Réponds en français de manière claire et professionnelle.', verbose_name='Prompt système')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assistant IA',
                'verbose_name_plural': 'Assistants IA',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message utilisateur')),
                ('response', models.TextField(verbose_name='Réponse IA')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('message_type', models.CharField(choices=[('question', 'Question'), ('general', 'Général'), ('vehicle', 'Véhicule'), ('maintenance', 'Maintenance')], default='question', max_length=20, verbose_name='Type de message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message de chat',
                'verbose_name_plural': 'Messages de chat',
                'ordering': ['-timestamp'],
            },
        ),
    ]
