# Generated by Django 4.2.7 on 2025-10-13 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("bug", "Signalement de Bug"),
                            ("suggestion", "Suggestion d'amélioration"),
                            ("question", "Question"),
                            ("compliment", "Compliment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "query_context",
                    models.TextField(
                        blank=True, help_text="Contexte de la requête si applicable"
                    ),
                ),
                ("resolved", models.BooleanField(default=False)),
                ("admin_response", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Message de Feedback",
                "verbose_name_plural": "Messages de Feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paramètre Système",
                "verbose_name_plural": "Paramètres Système",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rdf_uri",
                    models.URLField(
                        blank=True,
                        help_text="URI RDF de l'utilisateur dans l'ontologie",
                        null=True,
                    ),
                ),
                (
                    "transport_preferences",
                    models.JSONField(
                        default=dict, help_text="Préférences de transport en JSON"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil Utilisateur",
                "verbose_name_plural": "Profils Utilisateurs",
            },
        ),
        migrations.CreateModel(
            name="QueryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query_type",
                    models.CharField(
                        choices=[
                            ("natural", "Question Naturelle"),
                            ("sparql", "Requête SPARQL"),
                            ("predefined", "Requête Prédéfinie"),
                            ("api", "Requête API"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "original_query",
                    models.TextField(help_text="Question originale ou requête SPARQL"),
                ),
                (
                    "generated_sparql",
                    models.TextField(blank=True, help_text="SPARQL généré par l'IA"),
                ),
                ("results_count", models.IntegerField(default=0)),
                (
                    "execution_time",
                    models.FloatField(help_text="Temps d'exécution en secondes"),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal de Requête",
                "verbose_name_plural": "Journal des Requêtes",
                "ordering": ["-timestamp"],
            },
        ),
    ]
