# Generated by Django 4.2.7 on 2025-10-13 22:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("smartcity_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapteurTrafic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("code_capteur", models.CharField(max_length=50, unique=True)),
                (
                    "type_capteur",
                    models.CharField(
                        choices=[
                            ("boucle_magnetique", "Boucle Magnétique"),
                            ("camera_ia", "Caméra IA"),
                            ("radar", "Radar"),
                            ("lidar", "LiDAR"),
                            ("capteur_bluetooth", "Capteur Bluetooth"),
                            ("capteur_wifi", "Capteur Wi-Fi"),
                            ("gps_flottant", "Données GPS Flottantes"),
                        ],
                        max_length=50,
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "direction_mesure",
                    models.CharField(
                        help_text="Direction de la voie mesurée", max_length=100
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("inactif", "Inactif"),
                            ("maintenance", "En Maintenance"),
                            ("defaillant", "Défaillant"),
                        ],
                        default="actif",
                        max_length=20,
                    ),
                ),
                (
                    "frequence_mesure",
                    models.IntegerField(
                        default=60, help_text="Fréquence de mesure en secondes"
                    ),
                ),
                (
                    "precision_detection",
                    models.FloatField(
                        default=95.0, help_text="Précision de détection en pourcentage"
                    ),
                ),
                (
                    "vitesse_min_detection",
                    models.IntegerField(
                        default=5, help_text="Vitesse minimale détectée en km/h"
                    ),
                ),
                (
                    "vitesse_max_detection",
                    models.IntegerField(
                        default=200, help_text="Vitesse maximale détectée en km/h"
                    ),
                ),
                ("date_installation", models.DateField()),
                ("derniere_calibration", models.DateTimeField(blank=True, null=True)),
                ("prochaine_maintenance", models.DateField(blank=True, null=True)),
                ("fournisseur", models.CharField(blank=True, max_length=100)),
                ("modele", models.CharField(blank=True, max_length=100)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("derniere_mise_a_jour", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Capteur de Trafic",
                "verbose_name_plural": "Capteurs de Trafic",
                "ordering": ["zone_trafic", "nom"],
            },
        ),
        migrations.CreateModel(
            name="CritereTrajet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "poids_default",
                    models.FloatField(
                        default=1.0,
                        help_text="Poids par défaut dans l'algorithme d'optimisation",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "unite_mesure",
                    models.CharField(
                        help_text="Unité de mesure (minutes, km, €, etc.)",
                        max_length=50,
                    ),
                ),
                ("est_actif", models.BooleanField(default=True)),
                ("ordre_affichage", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name": "Critère de Trajet",
                "verbose_name_plural": "Critères de Trajet",
                "ordering": ["ordre_affichage", "nom"],
            },
        ),
        migrations.CreateModel(
            name="EquipementStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_equipement",
                    models.CharField(
                        choices=[
                            ("ascenseur", "Ascenseur"),
                            ("escalier_mecanique", "Escalier Mécanique"),
                            ("distributeur_tickets", "Distributeur de Tickets"),
                            ("borne_info", "Borne d'Information"),
                            ("wifi", "Wi-Fi Gratuit"),
                            ("wc", "Toilettes"),
                            ("consigne", "Consignes"),
                            ("parking_velo", "Parking Vélos"),
                            ("borne_recharge", "Borne de Recharge"),
                            ("eclairage", "Éclairage"),
                            ("videosurveillance", "Vidéosurveillance"),
                            ("guichet", "Guichet d'Accueil"),
                            ("commerces", "Commerces"),
                            ("banc", "Bancs"),
                            ("abri", "Abri"),
                        ],
                        max_length=50,
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("fonctionnel", "Fonctionnel"),
                            ("en_panne", "En Panne"),
                            ("maintenance", "En Maintenance"),
                            ("hors_service", "Hors Service"),
                        ],
                        default="fonctionnel",
                        max_length=20,
                    ),
                ),
                ("derniere_verification", models.DateTimeField(blank=True, null=True)),
                ("prochaine_maintenance", models.DateTimeField(blank=True, null=True)),
                (
                    "niveau",
                    models.CharField(
                        blank=True, help_text="Niveau ou étage", max_length=50
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        blank=True,
                        help_text="Zone spécifique dans la station",
                        max_length=100,
                    ),
                ),
                (
                    "specifications_techniques",
                    models.JSONField(blank=True, default=dict),
                ),
                ("fournisseur", models.CharField(blank=True, max_length=100)),
                ("modele", models.CharField(blank=True, max_length=100)),
                ("date_installation", models.DateField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("derniere_mise_a_jour", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Équipement de Station",
                "verbose_name_plural": "Équipements de Stations",
                "ordering": ["station", "type_equipement", "nom"],
            },
        ),
        migrations.CreateModel(
            name="ItinerairePropose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_itineraire", models.CharField(blank=True, max_length=200)),
                (
                    "algorithme_utilise",
                    models.CharField(
                        choices=[
                            ("plus_court", "Plus Court"),
                            ("plus_rapide", "Plus Rapide"),
                            ("moins_cher", "Moins Cher"),
                            ("eco_friendly", "Écologique"),
                            ("multimodal", "Multimodal Optimisé"),
                            ("personnalise", "Personnalisé"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "rang_proposition",
                    models.IntegerField(
                        default=1, help_text="Ordre de proposition (1 = meilleur)"
                    ),
                ),
                (
                    "distance_totale",
                    models.FloatField(help_text="Distance totale en km"),
                ),
                (
                    "duree_estimee",
                    models.IntegerField(help_text="Durée estimée en minutes"),
                ),
                (
                    "cout_total",
                    models.DecimalField(
                        decimal_places=2, help_text="Coût total estimé", max_digits=10
                    ),
                ),
                (
                    "emission_co2_totale",
                    models.FloatField(help_text="Émissions CO2 totales en g"),
                ),
                (
                    "segments",
                    models.JSONField(help_text="Détails des segments de l'itinéraire"),
                ),
                (
                    "score_optimisation",
                    models.FloatField(help_text="Score d'optimisation global"),
                ),
                ("avantages", models.JSONField(blank=True, default=list)),
                ("inconvenients", models.JSONField(blank=True, default=list)),
                ("valide_jusqu_a", models.DateTimeField()),
                ("conditions_trafic", models.CharField(blank=True, max_length=100)),
                ("conditions_meteo", models.CharField(blank=True, max_length=100)),
                ("selectionne_par_utilisateur", models.BooleanField(default=False)),
                ("date_selection", models.DateTimeField(blank=True, null=True)),
                ("date_calcul", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Itinéraire Proposé",
                "verbose_name_plural": "Itinéraires Proposés",
                "ordering": ["trajet", "rang_proposition"],
            },
        ),
        migrations.CreateModel(
            name="ModeTransport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("transport_public", "Transport Public"),
                            ("transport_actif", "Transport Actif"),
                            ("transport_prive", "Transport Privé"),
                            ("transport_partage", "Transport Partagé"),
                            ("transport_innovant", "Transport Innovant"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "icone",
                    models.CharField(
                        help_text="Classe CSS pour l'icône", max_length=50
                    ),
                ),
                ("couleur", models.CharField(default="#007bff", max_length=7)),
                (
                    "vitesse_moyenne",
                    models.FloatField(help_text="Vitesse moyenne en km/h"),
                ),
                (
                    "vitesse_maximale",
                    models.FloatField(
                        blank=True, help_text="Vitesse maximale en km/h", null=True
                    ),
                ),
                (
                    "rayon_action",
                    models.FloatField(help_text="Rayon d'action moyen en km"),
                ),
                (
                    "cout_fixe",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Coût fixe par trajet",
                        max_digits=10,
                    ),
                ),
                (
                    "cout_par_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Coût par kilomètre",
                        max_digits=10,
                    ),
                ),
                (
                    "cout_par_minute",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Coût par minute",
                        max_digits=10,
                    ),
                ),
                (
                    "emission_co2_par_km",
                    models.FloatField(default=0, help_text="Émissions CO2 en g/km"),
                ),
                (
                    "impact_environnemental",
                    models.IntegerField(
                        default=5,
                        help_text="Impact environnemental (1=très faible, 10=très élevé)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("accessible_pmr", models.BooleanField(default=False)),
                (
                    "age_minimum",
                    models.IntegerField(
                        default=0, help_text="Âge minimum pour utiliser ce mode"
                    ),
                ),
                ("permis_requis", models.BooleanField(default=False)),
                ("disponible_24h", models.BooleanField(default=False)),
                (
                    "conditions_meteo",
                    models.JSONField(
                        default=list, help_text="Conditions météo supportées"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("est_actif", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Mode de Transport",
                "verbose_name_plural": "Modes de Transport",
                "ordering": ["categorie", "nom"],
            },
        ),
        migrations.CreateModel(
            name="PreferencesCritere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "poids",
                    models.FloatField(
                        help_text="Importance de ce critère pour ce trajet",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "critere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smartcity_app.criteretrajet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Préférence de Critère",
                "verbose_name_plural": "Préférences de Critères",
            },
        ),
        migrations.CreateModel(
            name="RoleUtilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50, unique=True)),
                (
                    "type_role",
                    models.CharField(
                        choices=[
                            ("user", "Utilisateur Normal"),
                            ("admin", "Administrateur"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
                ("permissions_specifiques", models.JSONField(blank=True, default=list)),
                ("peut_voir_dashboard", models.BooleanField(default=False)),
                ("peut_voir_ontologie", models.BooleanField(default=False)),
                ("peut_gerer_utilisateurs", models.BooleanField(default=False)),
                ("peut_modifier_systeme", models.BooleanField(default=False)),
                ("peut_voir_stats_globales", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Rôle Utilisateur",
                "verbose_name_plural": "Rôles Utilisateur",
            },
        ),
        migrations.CreateModel(
            name="TypeStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("metro", "Station de Métro"),
                            ("bus", "Arrêt de Bus"),
                            ("tramway", "Station de Tramway"),
                            ("train", "Gare"),
                            ("velo_partage", "Station de Vélos Partagés"),
                            ("trottinette", "Station de Trottinettes"),
                            ("voiture_partage", "Station de Voitures Partagées"),
                            ("borne_recharge", "Borne de Recharge"),
                            ("parking", "Parking"),
                            ("multimodal", "Pôle Multimodal"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "icone",
                    models.CharField(
                        blank=True, help_text="Classe CSS pour l'icône", max_length=50
                    ),
                ),
                (
                    "couleur",
                    models.CharField(
                        default="#007bff",
                        help_text="Couleur hexadécimale",
                        max_length=7,
                    ),
                ),
                (
                    "capacite_moyenne",
                    models.IntegerField(
                        blank=True, help_text="Capacité moyenne d'accueil", null=True
                    ),
                ),
                ("accessible_pmr", models.BooleanField(default=False)),
                (
                    "couvert",
                    models.BooleanField(default=False, help_text="Station couverte"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("derniere_mise_a_jour", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Type de Station",
                "verbose_name_plural": "Types de Stations",
                "ordering": ["categorie", "nom"],
            },
        ),
        migrations.CreateModel(
            name="TypeVehicule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("transport_public", "Transport Public"),
                            ("vehicule_partage", "Véhicule Partagé"),
                            ("vehicule_prive", "Véhicule Privé"),
                            ("vehicule_service", "Véhicule de Service"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "mode_propulsion",
                    models.CharField(
                        choices=[
                            ("electrique", "Électrique"),
                            ("hybride", "Hybride"),
                            ("essence", "Essence"),
                            ("diesel", "Diesel"),
                            ("gaz", "Gaz"),
                            ("hydrogene", "Hydrogène"),
                            ("musculaire", "Musculaire"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "capacite_passagers",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "vitesse_max",
                    models.FloatField(
                        blank=True, help_text="Vitesse maximale en km/h", null=True
                    ),
                ),
                (
                    "autonomie",
                    models.FloatField(
                        blank=True, help_text="Autonomie en km", null=True
                    ),
                ),
                (
                    "emission_co2",
                    models.FloatField(default=0, help_text="Émissions CO2 en g/km"),
                ),
                (
                    "niveau_bruit",
                    models.IntegerField(
                        blank=True, help_text="Niveau de bruit en dB", null=True
                    ),
                ),
                (
                    "accessible_pmr",
                    models.BooleanField(
                        default=False,
                        help_text="Accessible aux personnes à mobilité réduite",
                    ),
                ),
                ("equipements_accessibilite", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("derniere_mise_a_jour", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Type de Véhicule",
                "verbose_name_plural": "Types de Véhicules",
                "ordering": ["categorie", "nom"],
            },
        ),
        migrations.CreateModel(
            name="ZoneTrafic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "type_zone",
                    models.CharField(
                        choices=[
                            ("centre_ville", "Centre-Ville"),
                            ("peripherie", "Périphérie"),
                            ("zone_industrielle", "Zone Industrielle"),
                            ("zone_residentielle", "Zone Résidentielle"),
                            ("zone_commerciale", "Zone Commerciale"),
                            ("autoroute", "Autoroute"),
                            ("rocade", "Rocade"),
                            ("pont", "Pont"),
                            ("tunnel", "Tunnel"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "coordonnees_zone",
                    models.JSONField(
                        help_text="Polygone définissant la zone (GeoJSON)"
                    ),
                ),
                (
                    "vitesse_limite",
                    models.IntegerField(help_text="Vitesse limite en km/h"),
                ),
                ("nombre_voies", models.IntegerField(default=2)),
                (
                    "sens_circulation",
                    models.CharField(default="bidirectionnel", max_length=50),
                ),
                ("restrictions_horaires", models.JSONField(blank=True, default=dict)),
                ("restrictions_vehicules", models.JSONField(blank=True, default=list)),
                ("zone_pietons", models.BooleanField(default=False)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("derniere_mise_a_jour", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Zone de Trafic",
                "verbose_name_plural": "Zones de Trafic",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Vehicule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_identification", models.CharField(max_length=50, unique=True)),
                ("immatriculation", models.CharField(blank=True, max_length=20)),
                ("localisation_actuelle", models.CharField(blank=True, max_length=200)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("maintenance", "En Maintenance"),
                            ("hors_service", "Hors Service"),
                            ("reserve", "Réservé"),
                        ],
                        default="actif",
                        max_length=20,
                    ),
                ),
                ("annee_fabrication", models.IntegerField(blank=True, null=True)),
                (
                    "kilometrage",
                    models.FloatField(default=0, help_text="Kilométrage total"),
                ),
                (
                    "niveau_batterie",
                    models.IntegerField(
                        blank=True,
                        help_text="Niveau de batterie en pourcentage",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("derniere_maintenance", models.DateTimeField(blank=True, null=True)),
                ("prochaine_maintenance", models.DateTimeField(blank=True, null=True)),
                ("date_mise_en_service", models.DateTimeField(auto_now_add=True)),
                ("derniere_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "type_vehicule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicules",
                        to="smartcity_app.typevehicule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Véhicule",
                "verbose_name_plural": "Véhicules",
                "ordering": ["type_vehicule", "numero_identification"],
            },
        ),
        migrations.CreateModel(
            name="UtilisationVehicule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heure_debut", models.DateTimeField()),
                ("heure_fin", models.DateTimeField(blank=True, null=True)),
                ("lieu_depart", models.CharField(max_length=200)),
                ("lieu_arrivee", models.CharField(blank=True, max_length=200)),
                (
                    "distance_parcourue",
                    models.FloatField(
                        blank=True, help_text="Distance en km", null=True
                    ),
                ),
                ("nombre_passagers", models.IntegerField(default=0)),
                (
                    "consommation_energie",
                    models.FloatField(
                        blank=True, help_text="Consommation en kWh ou L", null=True
                    ),
                ),
                ("conditions_meteo", models.CharField(blank=True, max_length=100)),
                ("niveau_trafic", models.CharField(blank=True, max_length=50)),
                (
                    "note_experience",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("commentaires", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utilisations",
                        to="smartcity_app.vehicule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisation de Véhicule",
                "verbose_name_plural": "Utilisations de Véhicules",
                "ordering": ["-heure_debut"],
            },
        ),
        migrations.CreateModel(
            name="UtilisationModeItineraire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distance",
                    models.FloatField(
                        help_text="Distance parcourue avec ce mode en km"
                    ),
                ),
                (
                    "duree",
                    models.IntegerField(help_text="Durée d'utilisation en minutes"),
                ),
                (
                    "cout",
                    models.DecimalField(
                        decimal_places=2, help_text="Coût pour ce mode", max_digits=10
                    ),
                ),
                (
                    "ordre_utilisation",
                    models.IntegerField(
                        help_text="Ordre d'utilisation dans l'itinéraire"
                    ),
                ),
                (
                    "informations_complementaires",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "itineraire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smartcity_app.itinerairepropose",
                    ),
                ),
                (
                    "mode_transport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smartcity_app.modetransport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisation de Mode",
                "verbose_name_plural": "Utilisations de Modes",
                "ordering": ["ordre_utilisation"],
                "unique_together": {
                    ("itineraire", "mode_transport", "ordre_utilisation")
                },
            },
        ),
        migrations.CreateModel(
            name="Trajet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_trajet", models.CharField(blank=True, max_length=200)),
                (
                    "type_trajet",
                    models.CharField(
                        choices=[
                            ("domicile_travail", "Domicile-Travail"),
                            ("travail_domicile", "Travail-Domicile"),
                            ("loisirs", "Loisirs"),
                            ("courses", "Courses"),
                            ("sante", "Santé"),
                            ("education", "Éducation"),
                            ("professionnel", "Professionnel"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=50,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("en_cours", "En Cours"),
                            ("termine", "Terminé"),
                            ("annule", "Annulé"),
                            ("reporte", "Reporté"),
                        ],
                        default="planifie",
                        max_length=20,
                    ),
                ),
                ("lieu_depart", models.CharField(max_length=200)),
                ("latitude_depart", models.FloatField()),
                ("longitude_depart", models.FloatField()),
                ("lieu_arrivee", models.CharField(max_length=200)),
                ("latitude_arrivee", models.FloatField()),
                ("longitude_arrivee", models.FloatField()),
                ("points_intermediaires", models.JSONField(blank=True, default=list)),
                ("date_heure_depart_souhaitee", models.DateTimeField()),
                (
                    "date_heure_arrivee_souhaitee",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "date_heure_depart_reelle",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "date_heure_arrivee_reelle",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "budget_maximum",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "duree_maximale",
                    models.IntegerField(
                        blank=True, help_text="Durée maximale en minutes", null=True
                    ),
                ),
                ("nombre_correspondances_max", models.IntegerField(default=3)),
                (
                    "distance_marche_max",
                    models.FloatField(
                        default=1.0, help_text="Distance de marche maximale en km"
                    ),
                ),
                ("necessite_accessibilite", models.BooleanField(default=False)),
                ("accompagne_enfants", models.BooleanField(default=False)),
                ("bagages_lourds", models.BooleanField(default=False)),
                ("est_recurrent", models.BooleanField(default=False)),
                ("frequence_recurrence", models.CharField(blank=True, max_length=50)),
                ("jours_semaine", models.JSONField(blank=True, default=list)),
                ("date_fin_recurrence", models.DateField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("derniere_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "criteres_optimisation",
                    models.ManyToManyField(
                        through="smartcity_app.PreferencesCritere",
                        to="smartcity_app.criteretrajet",
                    ),
                ),
                (
                    "modes_transport_acceptes",
                    models.ManyToManyField(
                        blank=True, to="smartcity_app.modetransport"
                    ),
                ),
                (
                    "modes_transport_refuses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="trajets_refuses",
                        to="smartcity_app.modetransport",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trajets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trajet",
                "verbose_name_plural": "Trajets",
                "ordering": ["-date_heure_depart_souhaitee"],
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("code_station", models.CharField(max_length=50, unique=True)),
                ("adresse", models.TextField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "altitude",
                    models.FloatField(
                        blank=True, help_text="Altitude en mètres", null=True
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("maintenance", "En Maintenance"),
                            ("fermee", "Fermée"),
                            ("construction", "En Construction"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "horaires_ouverture",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Horaires par jour de la semaine",
                    ),
                ),
                ("capacite_actuelle", models.IntegerField(blank=True, null=True)),
                ("capacite_maximale", models.IntegerField(blank=True, null=True)),
                (
                    "niveau_accessibilite",
                    models.CharField(
                        choices=[
                            ("totalement_accessible", "Totalement Accessible"),
                            ("partiellement_accessible", "Partiellement Accessible"),
                            ("non_accessible", "Non Accessible"),
                            ("en_cours_amenagement", "En Cours d'Aménagement"),
                        ],
                        default="non_accessible",
                        max_length=50,
                    ),
                ),
                (
                    "equipements_pmr",
                    models.TextField(
                        blank=True,
                        help_text="Équipements pour personnes à mobilité réduite",
                    ),
                ),
                ("zone_tarifaire", models.CharField(blank=True, max_length=50)),
                (
                    "lignes_desservies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste des lignes qui desservent cette station",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("informations_voyageurs", models.TextField(blank=True)),
                ("date_mise_en_service", models.DateField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("derniere_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "correspondances",
                    models.ManyToManyField(blank=True, to="smartcity_app.station"),
                ),
                (
                    "type_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stations",
                        to="smartcity_app.typestation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Station",
                "verbose_name_plural": "Stations",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="ProfilUtilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_naissance", models.DateField(blank=True, null=True)),
                ("telephone", models.CharField(blank=True, max_length=15)),
                ("adresse", models.TextField(blank=True)),
                (
                    "photo_profil",
                    models.ImageField(blank=True, null=True, upload_to="profils/"),
                ),
                (
                    "modes_transport_preferes",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "budget_transport_mensuel",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "temps_trajet_max_acceptable",
                    models.IntegerField(blank=True, help_text="En minutes", null=True),
                ),
                ("necessite_accessibilite", models.BooleanField(default=False)),
                ("type_handicap", models.CharField(blank=True, max_length=100)),
                ("preference_eco_friendly", models.BooleanField(default=False)),
                ("accepte_modes_alternatifs", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("derniere_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="smartcity_app.roleutilisateur",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil Utilisateur",
                "verbose_name_plural": "Profils Utilisateurs",
            },
        ),
        migrations.AddField(
            model_name="preferencescritere",
            name="trajet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="smartcity_app.trajet"
            ),
        ),
        migrations.CreateModel(
            name="PreferenceLocalisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_lieu", models.CharField(max_length=200)),
                (
                    "type_lieu",
                    models.CharField(
                        choices=[
                            ("domicile", "Domicile"),
                            ("travail", "Travail"),
                            ("ecole", "École"),
                            ("loisirs", "Loisirs"),
                            ("courses", "Courses"),
                            ("sante", "Santé"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("adresse", models.TextField()),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "frequence_visite",
                    models.IntegerField(
                        default=1, help_text="Nombre de visites par semaine"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "profil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lieux_favoris",
                        to="smartcity_app.profilutilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lieu Favori",
                "verbose_name_plural": "Lieux Favoris",
            },
        ),
        migrations.CreateModel(
            name="MaintenanceVehicule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_maintenance",
                    models.CharField(
                        choices=[
                            ("preventive", "Préventive"),
                            ("corrective", "Corrective"),
                            ("revision", "Révision"),
                            ("reparation", "Réparation"),
                            ("controle", "Contrôle Technique"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifiee", "Planifiée"),
                            ("en_cours", "En Cours"),
                            ("terminee", "Terminée"),
                            ("annulee", "Annulée"),
                        ],
                        default="planifiee",
                        max_length=20,
                    ),
                ),
                ("date_planifiee", models.DateTimeField()),
                ("date_debut_relle", models.DateTimeField(blank=True, null=True)),
                ("date_fin_relle", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField()),
                (
                    "technicien_responsable",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "cout_estime",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "cout_reel",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("pieces_changees", models.JSONField(blank=True, default=list)),
                ("materiel_utilise", models.TextField(blank=True)),
                ("problemes_detectes", models.TextField(blank=True)),
                ("actions_realisees", models.TextField(blank=True)),
                ("recommandations", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("derniere_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "vehicule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenances",
                        to="smartcity_app.vehicule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance de Véhicule",
                "verbose_name_plural": "Maintenances de Véhicules",
                "ordering": ["-date_planifiee"],
            },
        ),
        migrations.AddField(
            model_name="itinerairepropose",
            name="modes_transport",
            field=models.ManyToManyField(
                through="smartcity_app.UtilisationModeItineraire",
                to="smartcity_app.modetransport",
            ),
        ),
        migrations.AddField(
            model_name="itinerairepropose",
            name="trajet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itineraires_proposes",
                to="smartcity_app.trajet",
            ),
        ),
        migrations.CreateModel(
            name="IncidentStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_incident",
                    models.CharField(
                        choices=[
                            ("panne_equipement", "Panne d'Équipement"),
                            ("probleme_acces", "Problème d'Accessibilité"),
                            ("vandalisme", "Vandalisme"),
                            ("nettoyage", "Problème de Propreté"),
                            ("securite", "Problème de Sécurité"),
                            ("information", "Information Erronée"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "niveau_priorite",
                    models.CharField(
                        choices=[
                            ("basse", "Basse"),
                            ("normale", "Normale"),
                            ("haute", "Haute"),
                            ("critique", "Critique"),
                        ],
                        default="normale",
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("signale", "Signalé"),
                            ("en_cours", "En Cours de Traitement"),
                            ("resolu", "Résolu"),
                            ("ferme", "Fermé"),
                        ],
                        default="signale",
                        max_length=20,
                    ),
                ),
                ("signale_par", models.CharField(blank=True, max_length=100)),
                ("assigne_a", models.CharField(blank=True, max_length=100)),
                ("date_signalement", models.DateTimeField(auto_now_add=True)),
                ("date_prise_en_compte", models.DateTimeField(blank=True, null=True)),
                ("date_resolution", models.DateTimeField(blank=True, null=True)),
                ("actions_entreprises", models.TextField(blank=True)),
                ("commentaires_resolution", models.TextField(blank=True)),
                (
                    "cout_reparation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("derniere_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "equipement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="smartcity_app.equipementstation",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="smartcity_app.station",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident de Station",
                "verbose_name_plural": "Incidents de Stations",
                "ordering": ["-date_signalement"],
            },
        ),
        migrations.CreateModel(
            name="HistoriqueActivite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_activite",
                    models.CharField(
                        choices=[
                            ("recherche_trajet", "Recherche de trajet"),
                            ("planification_trajet", "Planification de trajet"),
                            ("evaluation_trajet", "Évaluation de trajet"),
                            ("modification_profil", "Modification du profil"),
                            ("consultation_info", "Consultation d'informations"),
                            ("signalement", "Signalement"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("donnees_contexte", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "profil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="smartcity_app.profilutilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activité Utilisateur",
                "verbose_name_plural": "Activités Utilisateur",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="FeuSignalisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("code_feu", models.CharField(max_length=50, unique=True)),
                (
                    "type_feu",
                    models.CharField(
                        choices=[
                            ("tricolore_standard", "Tricolore Standard"),
                            ("tricolore_pietons", "Tricolore avec Piétons"),
                            ("clignotant", "Feu Clignotant"),
                            ("feu_priorite", "Feu de Priorité"),
                            ("panneau_variable", "Panneau à Message Variable"),
                        ],
                        max_length=50,
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "carrefour",
                    models.CharField(
                        help_text="Description du carrefour", max_length=200
                    ),
                ),
                (
                    "mode_fonctionnement",
                    models.CharField(
                        choices=[
                            ("automatique", "Automatique"),
                            ("adaptatif", "Adaptatif au Trafic"),
                            ("coordonne", "Coordonné"),
                            ("manuel", "Manuel"),
                            ("maintenance", "Mode Maintenance"),
                        ],
                        default="automatique",
                        max_length=50,
                    ),
                ),
                (
                    "cycle_standard",
                    models.JSONField(
                        default=dict, help_text="Configuration du cycle standard"
                    ),
                ),
                ("priorite_pietons", models.BooleanField(default=False)),
                ("priorite_transports", models.BooleanField(default=False)),
                (
                    "seuil_adaptation_trafic",
                    models.IntegerField(
                        default=80, help_text="Seuil de déclenchement adaptation (%)"
                    ),
                ),
                (
                    "temps_reponse_max",
                    models.IntegerField(
                        default=300, help_text="Temps de réponse maximum en secondes"
                    ),
                ),
                ("phase_actuelle", models.CharField(blank=True, max_length=50)),
                (
                    "temps_restant_phase",
                    models.IntegerField(
                        blank=True, help_text="Temps restant en secondes", null=True
                    ),
                ),
                ("statut", models.CharField(default="actif", max_length=20)),
                ("derniere_maintenance", models.DateTimeField(blank=True, null=True)),
                ("prochaine_maintenance", models.DateField(blank=True, null=True)),
                ("date_installation", models.DateField()),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("derniere_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "capteurs_associes",
                    models.ManyToManyField(
                        blank=True, to="smartcity_app.capteurtrafic"
                    ),
                ),
                (
                    "zone_trafic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feux",
                        to="smartcity_app.zonetrafic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feu de Signalisation",
                "verbose_name_plural": "Feux de Signalisation",
                "ordering": ["zone_trafic", "nom"],
            },
        ),
        migrations.CreateModel(
            name="EvenementTrafic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("accident", "Accident"),
                            ("travaux", "Travaux"),
                            ("manifestation", "Manifestation"),
                            ("evenement_sportif", "Événement Sportif"),
                            ("evenement_culturel", "Événement Culturel"),
                            ("conditions_meteo", "Conditions Météorologiques"),
                            ("panne_infrastructure", "Panne d'Infrastructure"),
                            ("fermeture_voie", "Fermeture de Voie"),
                            ("deviation", "Déviation"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "niveau_impact",
                    models.CharField(
                        choices=[
                            ("faible", "Impact Faible"),
                            ("modere", "Impact Modéré"),
                            ("important", "Impact Important"),
                            ("majeur", "Impact Majeur"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rayon_impact",
                    models.FloatField(
                        blank=True, help_text="Rayon d'impact en kilomètres", null=True
                    ),
                ),
                ("date_debut", models.DateTimeField()),
                ("date_fin_prevue", models.DateTimeField()),
                ("date_fin_reelle", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("prevu", "Prévu"),
                            ("en_cours", "En Cours"),
                            ("termine", "Terminé"),
                            ("annule", "Annulé"),
                        ],
                        default="prevu",
                        max_length=20,
                    ),
                ),
                ("deviations_proposees", models.TextField(blank=True)),
                ("transports_alternatifs", models.TextField(blank=True)),
                ("recommandations", models.TextField(blank=True)),
                ("communique_presse", models.TextField(blank=True)),
                ("canaux_diffusion", models.JSONField(blank=True, default=list)),
                ("responsable", models.CharField(blank=True, max_length=100)),
                ("services_impliques", models.JSONField(blank=True, default=list)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("derniere_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "zones_affectees",
                    models.ManyToManyField(to="smartcity_app.zonetrafic"),
                ),
            ],
            options={
                "verbose_name": "Événement de Trafic",
                "verbose_name_plural": "Événements de Trafic",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationTrajet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_duree",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "note_cout",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "note_confort",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "note_ponctualite",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "note_facilite",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "note_globale",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("points_positifs", models.TextField(blank=True)),
                ("points_negatifs", models.TextField(blank=True)),
                ("suggestions_amelioration", models.TextField(blank=True)),
                ("recommanderait", models.BooleanField(null=True)),
                ("reutiliserait_itineraire", models.BooleanField(null=True)),
                ("incidents_rencontres", models.JSONField(blank=True, default=list)),
                ("date_evaluation", models.DateTimeField(auto_now_add=True)),
                (
                    "itineraire_utilise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="smartcity_app.itinerairepropose",
                    ),
                ),
                (
                    "trajet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="smartcity_app.trajet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Évaluation de Trajet",
                "verbose_name_plural": "Évaluations de Trajets",
            },
        ),
        migrations.AddField(
            model_name="equipementstation",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipements",
                to="smartcity_app.station",
            ),
        ),
        migrations.CreateModel(
            name="DonneesTrafic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "nombre_vehicules",
                    models.IntegerField(
                        default=0, help_text="Nombre de véhicules détectés"
                    ),
                ),
                (
                    "vitesse_moyenne",
                    models.FloatField(
                        blank=True, help_text="Vitesse moyenne en km/h", null=True
                    ),
                ),
                (
                    "vitesse_mediane",
                    models.FloatField(
                        blank=True, help_text="Vitesse médiane en km/h", null=True
                    ),
                ),
                (
                    "debit_vehicules",
                    models.FloatField(
                        blank=True, help_text="Débit en véhicules/heure", null=True
                    ),
                ),
                ("vehicules_legers", models.IntegerField(default=0)),
                ("vehicules_lourds", models.IntegerField(default=0)),
                ("deux_roues", models.IntegerField(default=0)),
                ("transports_publics", models.IntegerField(default=0)),
                (
                    "niveau_congestion",
                    models.CharField(
                        choices=[
                            ("fluide", "Trafic Fluide"),
                            ("dense", "Trafic Dense"),
                            ("ralenti", "Trafic Ralenti"),
                            ("bouchon", "Bouchon"),
                            ("bloque", "Circulation Bloquée"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "taux_occupation",
                    models.FloatField(
                        help_text="Taux d'occupation de la voie en pourcentage",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("conditions_meteo", models.CharField(blank=True, max_length=100)),
                (
                    "visibilite",
                    models.IntegerField(
                        blank=True, help_text="Visibilité en mètres", null=True
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        blank=True, help_text="Température en °C", null=True
                    ),
                ),
                ("incident_detecte", models.BooleanField(default=False)),
                ("type_incident", models.CharField(blank=True, max_length=100)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "capteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donnees",
                        to="smartcity_app.capteurtrafic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Données de Trafic",
                "verbose_name_plural": "Données de Trafic",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="capteurtrafic",
            name="zone_trafic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="capteurs",
                to="smartcity_app.zonetrafic",
            ),
        ),
        migrations.AddIndex(
            model_name="trajet",
            index=models.Index(
                fields=["utilisateur", "statut"], name="smartcity_a_utilisa_40670f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trajet",
            index=models.Index(
                fields=["date_heure_depart_souhaitee"],
                name="smartcity_a_date_he_f726b1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trajet",
            index=models.Index(
                fields=["type_trajet"], name="smartcity_a_type_tr_3d4593_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="station",
            index=models.Index(
                fields=["latitude", "longitude"], name="smartcity_a_latitud_18f9be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="station",
            index=models.Index(
                fields=["code_station"], name="smartcity_a_code_st_ff01a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="station",
            index=models.Index(fields=["statut"], name="smartcity_a_statut_80522c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="preferencescritere",
            unique_together={("trajet", "critere")},
        ),
        migrations.AddIndex(
            model_name="donneestrafic",
            index=models.Index(
                fields=["timestamp"], name="smartcity_a_timesta_0ca52c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donneestrafic",
            index=models.Index(
                fields=["capteur", "timestamp"], name="smartcity_a_capteur_bdf05f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donneestrafic",
            index=models.Index(
                fields=["niveau_congestion"], name="smartcity_a_niveau__d15624_idx"
            ),
        ),
    ]
