# Generated by Django 4.2.7 on 2025-10-14 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "smartcity_app",
            "0002_capteurtrafic_criteretrajet_equipementstation_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeTrajetIntelligent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "lieu_depart",
                    models.CharField(max_length=300, verbose_name="Lieu de départ"),
                ),
                (
                    "lieu_depart_lat",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Latitude départ"
                    ),
                ),
                (
                    "lieu_depart_lng",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Longitude départ"
                    ),
                ),
                (
                    "lieu_arrivee",
                    models.CharField(max_length=300, verbose_name="Lieu d'arrivée"),
                ),
                (
                    "lieu_arrivee_lat",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Latitude arrivée"
                    ),
                ),
                (
                    "lieu_arrivee_lng",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Longitude arrivée"
                    ),
                ),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("rapidite", "Le plus rapide"),
                            ("economique", "Le moins cher"),
                            ("ecologique", "Le plus écologique"),
                            ("confort", "Le plus confortable"),
                            ("moins_circulation", "Éviter la circulation"),
                        ],
                        default="rapidite",
                        max_length=20,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "heure_depart_souhaitee",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Heure de départ souhaitée"
                    ),
                ),
                (
                    "heure_arrivee_souhaitee",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Heure d'arrivée souhaitée"
                    ),
                ),
                (
                    "budget_maximum",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Budget maximum (€)"
                    ),
                ),
                (
                    "duree_maximum",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Durée maximum (minutes)"
                    ),
                ),
                (
                    "accessible_pmr",
                    models.BooleanField(default=False, verbose_name="Accessible PMR"),
                ),
                (
                    "eviter_circulation",
                    models.BooleanField(
                        default=False, verbose_name="Éviter la circulation"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("en_cours", "Calcul en cours"),
                            ("complete", "Complétée"),
                            ("erreur", "Erreur"),
                        ],
                        default="en_attente",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "resultats_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Résultats calculés"
                    ),
                ),
                (
                    "score_satisfaction",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Score de satisfaction"
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de Trajet Intelligent",
                "verbose_name_plural": "Demandes de Trajets Intelligents",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="TypeVehiculeIntelligent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Nom du véhicule"),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("public", "Transport Public"),
                            ("prive", "Transport Privé"),
                            ("partage", "Transport Partagé"),
                            ("actif", "Transport Actif"),
                        ],
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "icone",
                    models.CharField(
                        default="fas fa-car", max_length=50, verbose_name="Icône"
                    ),
                ),
                (
                    "couleur",
                    models.CharField(
                        default="#007bff", max_length=7, verbose_name="Couleur"
                    ),
                ),
                (
                    "vitesse_moyenne",
                    models.FloatField(
                        default=30.0, verbose_name="Vitesse moyenne (km/h)"
                    ),
                ),
                (
                    "cout_par_km",
                    models.FloatField(default=0.0, verbose_name="Coût par km (€)"),
                ),
                (
                    "empreinte_carbone",
                    models.FloatField(default=0.0, verbose_name="CO2 par km (g)"),
                ),
                (
                    "disponible",
                    models.BooleanField(default=True, verbose_name="Disponible"),
                ),
                (
                    "capacite_passagers",
                    models.IntegerField(default=1, verbose_name="Capacité passagers"),
                ),
                (
                    "accessible_pmr",
                    models.BooleanField(default=False, verbose_name="Accessible PMR"),
                ),
                (
                    "frequence_passage",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Fréquence passage (minutes)",
                    ),
                ),
                (
                    "horaires_service",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Horaires de service"
                    ),
                ),
            ],
            options={
                "verbose_name": "Type de Véhicule Intelligent",
                "verbose_name_plural": "Types de Véhicules Intelligents",
                "ordering": ["categorie", "nom"],
            },
        ),
        migrations.AlterField(
            model_name="profilutilisateur",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="smartcity_app.roleutilisateur",
            ),
        ),
        migrations.CreateModel(
            name="TrajetRecommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rang", models.IntegerField(verbose_name="Classement")),
                (
                    "etapes_json",
                    models.JSONField(
                        default=list, verbose_name="Étapes détaillées du trajet"
                    ),
                ),
                ("duree_minutes", models.IntegerField(verbose_name="Durée (minutes)")),
                ("distance_km", models.FloatField(verbose_name="Distance (km)")),
                ("cout_total", models.FloatField(verbose_name="Coût total (€)")),
                (
                    "empreinte_carbone_g",
                    models.FloatField(verbose_name="Empreinte carbone (g CO2)"),
                ),
                (
                    "score_confort",
                    models.IntegerField(default=5, verbose_name="Score confort (1-10)"),
                ),
                (
                    "niveau_circulation",
                    models.CharField(
                        choices=[
                            ("faible", "Faible"),
                            ("moyen", "Moyen"),
                            ("fort", "Fort"),
                        ],
                        default="moyen",
                        max_length=20,
                        verbose_name="Niveau de circulation",
                    ),
                ),
                (
                    "retard_estime",
                    models.IntegerField(
                        default=0, verbose_name="Retard estimé (minutes)"
                    ),
                ),
                (
                    "fiabilite_score",
                    models.FloatField(
                        default=8.0, verbose_name="Score de fiabilité (1-10)"
                    ),
                ),
                (
                    "alertes_trafic",
                    models.JSONField(default=list, verbose_name="Alertes trafic"),
                ),
                (
                    "horaires_transport",
                    models.JSONField(
                        default=dict, verbose_name="Horaires transport public"
                    ),
                ),
                (
                    "conditions_meteo",
                    models.JSONField(default=dict, verbose_name="Conditions météo"),
                ),
                ("score_ia", models.FloatField(verbose_name="Score calculé par l'IA")),
                (
                    "facteurs_decision",
                    models.JSONField(
                        default=list, verbose_name="Facteurs de décision IA"
                    ),
                ),
                (
                    "demande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trajets_ia",
                        to="smartcity_app.demandetrajetintelligent",
                        verbose_name="Demande",
                    ),
                ),
                (
                    "vehicules_utilises",
                    models.ManyToManyField(
                        to="smartcity_app.typevehiculeintelligent",
                        verbose_name="Véhicules utilisés",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trajet Recommandé IA",
                "verbose_name_plural": "Trajets Recommandés IA",
                "ordering": ["demande", "rang"],
            },
        ),
        migrations.CreateModel(
            name="PreferenceUtilisateurIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priorite_defaut",
                    models.CharField(
                        choices=[
                            ("rapidite", "Le plus rapide"),
                            ("economique", "Le moins cher"),
                            ("ecologique", "Le plus écologique"),
                            ("confort", "Le plus confortable"),
                            ("moins_circulation", "Éviter la circulation"),
                        ],
                        default="rapidite",
                        max_length=20,
                        verbose_name="Priorité par défaut",
                    ),
                ),
                (
                    "budget_defaut",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Budget par défaut (€)"
                    ),
                ),
                (
                    "duree_max_defaut",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Durée max par défaut (min)"
                    ),
                ),
                (
                    "necessite_pmr",
                    models.BooleanField(
                        default=False, verbose_name="Nécessite accessibilité PMR"
                    ),
                ),
                (
                    "tolerance_marche",
                    models.IntegerField(
                        default=10, verbose_name="Tolérance marche (minutes)"
                    ),
                ),
                (
                    "preference_directe",
                    models.BooleanField(
                        default=False, verbose_name="Préfère trajets directs"
                    ),
                ),
                (
                    "apprentissage_actif",
                    models.BooleanField(
                        default=True, verbose_name="Apprentissage automatique actif"
                    ),
                ),
                (
                    "poids_historique",
                    models.FloatField(
                        default=0.3,
                        verbose_name="Poids de l'historique dans les recommandations",
                    ),
                ),
                (
                    "recevoir_alertes",
                    models.BooleanField(
                        default=True, verbose_name="Recevoir les alertes"
                    ),
                ),
                (
                    "avance_notification",
                    models.IntegerField(
                        default=10, verbose_name="Avance notification (minutes)"
                    ),
                ),
                (
                    "notification_retards",
                    models.BooleanField(
                        default=True, verbose_name="Notifications retards"
                    ),
                ),
                (
                    "notification_alternatives",
                    models.BooleanField(
                        default=True, verbose_name="Proposer alternatives"
                    ),
                ),
                (
                    "lieux_favoris",
                    models.JSONField(
                        default=list, verbose_name="Lieux favoris avec coordonnées"
                    ),
                ),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences_transport_ia",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
                (
                    "vehicules_evites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="evites_par",
                        to="smartcity_app.typevehiculeintelligent",
                        verbose_name="Véhicules à éviter",
                    ),
                ),
                (
                    "vehicules_favoris",
                    models.ManyToManyField(
                        blank=True,
                        to="smartcity_app.typevehiculeintelligent",
                        verbose_name="Véhicules favoris",
                    ),
                ),
            ],
            options={
                "verbose_name": "Préférence Utilisateur IA",
                "verbose_name_plural": "Préférences Utilisateurs IA",
            },
        ),
        migrations.AddField(
            model_name="demandetrajetintelligent",
            name="vehicules_preferes",
            field=models.ManyToManyField(
                blank=True,
                to="smartcity_app.typevehiculeintelligent",
                verbose_name="Véhicules préférés",
            ),
        ),
        migrations.CreateModel(
            name="AlerteTransportTempsReel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_alerte",
                    models.CharField(
                        choices=[
                            ("retard", "Retard"),
                            ("annulation", "Annulation"),
                            ("perturbation", "Perturbation"),
                            ("maintenance", "Maintenance"),
                            ("incident", "Incident"),
                            ("circulation", "Circulation dense"),
                            ("meteo", "Conditions météo"),
                            ("info", "Information"),
                        ],
                        max_length=20,
                        verbose_name="Type d'alerte",
                    ),
                ),
                (
                    "severite",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("attention", "Attention"),
                            ("important", "Important"),
                            ("critique", "Critique"),
                        ],
                        default="info",
                        max_length=15,
                        verbose_name="Sévérité",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "ligne_transport",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Ligne de transport"
                    ),
                ),
                (
                    "zone_geographique",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Zone géographique"
                    ),
                ),
                (
                    "coordonnees_lat",
                    models.FloatField(blank=True, null=True, verbose_name="Latitude"),
                ),
                (
                    "coordonnees_lng",
                    models.FloatField(blank=True, null=True, verbose_name="Longitude"),
                ),
                ("date_debut", models.DateTimeField(verbose_name="Date de début")),
                (
                    "date_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de fin"
                    ),
                ),
                (
                    "duree_estimee",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Durée estimée (minutes)"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="System", max_length=100, verbose_name="Source"
                    ),
                ),
                (
                    "vehicule_concerne",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smartcity_app.typevehiculeintelligent",
                        verbose_name="Véhicule concerné",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte Transport Temps Réel",
                "verbose_name_plural": "Alertes Transport Temps Réel",
                "ordering": ["-date_creation"],
            },
        ),
    ]
