# Generated by Django 5.2.7 on 2025-10-26 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcity_app', '0003_demandetrajetintelligent_typevehiculeintelligent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Assistant Véhicules', max_length=100, verbose_name="Nom de l'assistant")),
                ('system_prompt', models.TextField(default='Tu es un assistant spécialisé dans la gestion de véhicules et la maintenance automobile. Tu peux aider avec les diagnostics, les conseils de maintenance, les réparations et toutes questions liées aux véhicules.', verbose_name='Prompt système')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assistant IA',
                'verbose_name_plural': 'Assistants IA',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message utilisateur')),
                ('response', models.TextField(verbose_name='Réponse IA')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('message_type', models.CharField(choices=[('question', 'Question'), ('maintenance', 'Maintenance'), ('diagnostic', 'Diagnostic'), ('general', 'Général')], default='question', max_length=20, verbose_name='Type de message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message de chat',
                'verbose_name_plural': 'Messages de chat',
                'ordering': ['-timestamp'],
            },
        ),
    ]
